### ISSUE TITLE
Update jobs milestone/11 branch to be synchronized with main

### ISSUE THREAD

**Issue by jchuahtacc** [tapis-project/tapis-ui#241]
- [ ] Merge main up to milestone/11
- [ ] Update packages with new @tapis/tapis-typescript-apps and @tapis/tapis-typescript-jobs packages (but do not move @tapis/typescript forward)
- [ ] Comment/disable UI elements that would cause react-query schema to not match new apps and job schemas
